### ISSUE TITLE
CentOS 6.5 image with 30GB root disk

### ISSUE THREAD

**Issue by konstan** [StratusLab/image-recipes#24]
Could you please generate a new CentOS image with 30GB root disk?  The disk needs to have minimum 20GB of free space.
Thank you in advance.

**Comment by rybkine** [comment]
The ID is
Ovo1LvwVgNUKhKCBSxUC_Endq9B

**Comment by konstan** [comment]
This is great!  Thank you.  We will try it tomorrow.

**Comment by konstan** [comment]
It worked perfectly for us.  Please close the issue.  Thank you very much!
